### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by christianhwa** [xiph/speexdsp#19] opened 2018-07-18 18:54 UTC
When it gets to this line: st = speex_preprocess_state_init(frame_size, 16000); I get the error message ld: symbol(s) not found for architecture x86_64. Any way for me to resolve this? Thanks!

**Comment by tmatth** [comment] 2019-09-26 13:00
It sounds like you're having trouble using/linking your code with speexdsp, but that's not a bug in speexdsp itself. Closing.

**Closed by tmatth** 2019-09-26 13:00 UTC
